#!/bin/sh
# vsx-idgate.sh EMU GOLDENDIR OUTDIR [MODE]
#
# The emitted-code identity gate (VSX-REGISTER-CLASSES.md §10 Stage 0).
#
# Captures POWERARM_CODEHASHLOG per GUEST BINARY rather than once for the whole
# suite. That matters: the suite's static -nostdlib test programs all start at
# about the same guest address, so one shared log keys different programs' blocks
# to the same RIP and compares as noise. Measured: one shared log differs from
# ITSELF, same binary two runs, by 5k-72k of 133k triples -- more than any real
# codegen change would.
#
# Each binary runs alone, under setarch -R, single guest thread where the test
# allows it, into its own file. Compare two OUTDIRs with `diff -r`.
#
# MODE (optional) is extra environment, e.g. POWERARM_HOSTFEATURES=disableisa30.
set -u
emu=${1:?usage: vsx-idgate.sh EMU GOLDENDIR OUTDIR [MODE...]}
gold=${2:?usage: vsx-idgate.sh EMU GOLDENDIR OUTDIR [MODE...]}
out=${3:?usage: vsx-idgate.sh EMU GOLDENDIR OUTDIR [MODE...]}
shift 3
mkdir -p "$out" || exit 2
cd "$gold" || exit 2

# Tests whose set of compiled blocks is not a function of the program: they
# create threads or fork, so block coverage follows the scheduler. Their
# codegen is still covered -- by every other test that compiles the same
# lowerings -- and including them would reintroduce the noise this script
# exists to remove.
nondet=' threadexit threadexit_loop sigteardown forkexec exclusive_contend exclusive_pair litmus lse lsecasp lseminmax rootfs_overlay '

# Only the assembly tests take part, which is every test built from a `*.S`
# (hand-written or generated by gen.py / gen_simd.py) -- i.e. the whole SIMD and
# FP corpus this work touches. They are `-nostdlib -static`, make no syscall
# whose result steers control flow, and were measured bit-stable: three
# consecutive captures of one binary agree on all 80 logs and 85901 blocks.
#
# The `*.c` tests are excluded, measured rather than assumed: they translate
# musl and talk to /proc, signals and timers, so WHICH blocks they reach varies
# run to run -- eleven of them disagree between two captures of one binary. So
# do the vDSO and thunk tests, whose guest-side shared object the build relinks
# on every ninja invocation. Their codegen is not unexamined: every lowering
# they reach is also reached by the assembly corpus.

count=0
skipped=0
for golden in *.golden; do
  t=${golden%.golden}
  case "$nondet" in *" $t "*) continue ;; esac
  bin=$t
  [ -f "$t.bin" ] && bin=$(cat "$t.bin")
  [ -x "./$bin" ] || continue
  [ -f "$t.S" ] || { skipped=$((skipped + 1)); continue; }
  args=''
  [ -f "$t.args" ] && args=$(cat "$t.args")
  envs=''
  [ -f "$t.env" ] && envs=$(cat "$t.env")
  # shellcheck disable=SC2086
  env $envs "$@" POWERARM_CODEHASHLOG="$out/$t.hash" \
    setarch -R "$emu" "./$bin" $args >/dev/null 2>&1
  # Sort: within one program the compile ORDER can still vary (link-time
  # thunk patching compiles successors on first traversal), the SET cannot.
  if [ -f "$out/$t.hash" ]; then
    sort -o "$out/$t.hash" "$out/$t.hash"
    count=$((count + 1))
  fi
done
echo "vsx-idgate: $count per-test hash logs in $out ($skipped non-assembly tests skipped)"
