#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Generates the differential A64Frontend test programs.

Each generated program is a list of cases. A case loads operands into
registers (LDR literal), sets NZCV (MSR), runs one instruction or a short
sequence, and calls `dump` (common.S), which prints every GPR, SP and NZCV.
The Pi's output is the golden; POWERarm's output must match it byte for byte.

Inputs are an edge-case corpus plus seeded random values, so a rerun
generates identical programs.

Usage: gen.py OUTDIR
"""

import os
import random
import sys

SEED = 0x41363446

EDGE64 = [
    0, 1, 2, 0x7F, 0x80, 0xFF, 0x7FFF, 0x8000, 0xFFFF,
    0x7FFFFFFF, 0x80000000, 0xFFFFFFFF, 0x100000000, 0x17FFFFFFF,
    0x7FFFFFFFFFFFFFFF, 0x8000000000000000, 0xFFFFFFFFFFFFFFFF,
    0xFFFFFFFFFFFFFFFE, 0xFFFFFFFF80000000, 0x00000000FFFFFFFE,
    0x123456789ABCDEF0, 0xFEDCBA9876543210, 0xDEADBEEF00000001,
]

# Registers a case may use for operands and results. A mix of statically
# allocated guest registers (X0-X8, X19-X24, X29) and context-backed ones
# (X9-X18, X25-X28). X30 is left alone: `bl dump` writes it.
REGS = [0, 1, 2, 3, 4, 7, 8, 9, 10, 15, 18, 19, 22, 25, 28, 29]

NZCV_VALUES = [0x0, 0x2, 0x4, 0x6, 0x8, 0x9, 0xA, 0xF, 0x1, 0x5, 0xC, 0x3]

CONDS = ["eq", "ne", "cs", "cc", "mi", "pl", "vs", "vc", "hi", "ls", "ge", "lt", "gt", "le", "al", "nv"]

SHIFTS = ["lsl", "lsr", "asr"]
EXTENDS = ["uxtb", "uxth", "uxtw", "uxtx", "sxtb", "sxth", "sxtw", "sxtx"]


class Program:
    def __init__(self, name, rng):
        self.name = name
        self.rng = rng
        self.lines = []
        self.cases = 0

    def emit(self, text):
        self.lines.append(text)

    def value(self):
        r = self.rng.random()
        if r < 0.45:
            return self.rng.choice(EDGE64)
        if r < 0.6:
            return self.rng.getrandbits(8)
        if r < 0.75:
            return self.rng.getrandbits(32)
        return self.rng.getrandbits(64)

    def reg(self):
        return self.rng.choice(REGS)

    def distinct_regs(self, n):
        return self.rng.sample(REGS, n)

    def load(self, reg, value):
        self.emit(f"        ldr     x{reg}, =0x{value & 0xFFFFFFFFFFFFFFFF:x}")

    def flags(self, nzcv=None):
        if nzcv is None:
            nzcv = self.rng.choice(NZCV_VALUES)
        self.emit(f"        mov     x17, #0x{nzcv << 28:x}")
        self.emit("        msr     nzcv, x17")

    def case(self, body, loads=None, nzcv=None, dumpbuf=False, desc=None):
        """body: list of instruction lines. loads: {reg: value}. desc: the
        case's comment, when the body is too long to spell out."""
        self.cases += 1
        self.emit(f"        // case {self.cases}: {desc or ' ; '.join(body)}")
        for reg, value in (loads or {}).items():
            self.load(reg, value)
        self.flags(nzcv)
        for line in body:
            self.emit(f"        {line}")
        self.emit("        bl      dump")
        if dumpbuf:
            self.emit("        bl      dumpbuf")
        if self.cases % 16 == 0:
            self.emit("        b       1f")
            self.emit("        .ltorg")
            self.emit("1:")

    def write(self, outdir):
        path = os.path.join(outdir, f"{self.name}.S")
        with open(path, "w") as f:
            f.write(f"// Generated by gen.py (seed 0x{SEED:x}). Do not edit.\n")
            f.write('#include "common.S"\n')
            f.write("        test_start\n")
            f.write("\n".join(self.lines))
            f.write("\n        test_exit\n        .ltorg\n")


def w(reg):
    return f"w{reg}"


def x(reg):
    return f"x{reg}"


def gen_addsub(p):
    for _ in range(480):
        is64 = p.rng.random() < 0.6
        rn = x if is64 else w
        d, n, m = p.reg(), p.reg(), p.reg()
        loads = {n: p.value(), m: p.value()}
        kind = p.rng.randrange(6)
        op = p.rng.choice(["add", "adds", "sub", "subs"])
        if kind == 0:
            imm = p.rng.choice([0, 1, 4095, p.rng.randrange(4096)])
            sh = p.rng.choice(["", ", lsl #12"])
            p.case([f"{op} {rn(d)}, {rn(n)}, #{imm}{sh}"], loads)
        elif kind == 1:
            amt = p.rng.choice([0, 1, 7, 31] + ([32, 63] if is64 else []))
            sh = p.rng.choice(SHIFTS)
            p.case([f"{op} {rn(d)}, {rn(n)}, {rn(m)}, {sh} #{amt}"], loads)
        elif kind == 2:
            ext = p.rng.choice(EXTENDS)
            amt = p.rng.randrange(5)
            src = x(m) if ext in ("uxtx", "sxtx") else w(m)
            if not is64:
                src = w(m)
            p.case([f"{op} {rn(d)}, {rn(n)}, {src}, {ext} #{amt}"], loads)
        elif kind == 3:
            cmp = p.rng.choice(["cmp", "cmn"])
            if p.rng.random() < 0.5:
                imm = p.rng.choice([0, 1, 31, 4095, p.rng.randrange(4096)])
                p.case([f"{cmp} {rn(n)}, #{imm}"], loads)
            else:
                p.case([f"{cmp} {rn(n)}, {rn(m)}"], loads)
        elif kind == 4:
            neg = p.rng.choice(["neg", "negs"])
            p.case([f"{neg} {rn(d)}, {rn(m)}"], loads)
        else:
            # SP as base and destination. SP is a static stack here, so its
            # value prints the same on both machines.
            imm = p.rng.choice([0, 8, 16, 4095])
            if is64:
                p.case([f"sub sp, sp, #{imm}", f"add {x(d)}, sp, #{imm}", f"add sp, sp, #{imm}"], loads)
            else:
                p.case([f"add {w(d)}, wsp, #{imm}"], loads)
    # Extended register with SP: add sp/xN, sp, wM, uxtw #s.
    for _ in range(20):
        d, m = p.reg(), p.reg()
        ext = p.rng.choice(["uxtw", "sxtw", "uxtb", "sxth", "lsl"])
        amt = p.rng.randrange(5)
        src = x(m) if ext == "lsl" else w(m)
        p.case([f"add {x(d)}, sp, {src}, {ext} #{amt}", f"cmp sp, {src}, {ext} #{amt}"], {m: p.rng.getrandbits(12)})


def gen_adc(p):
    for _ in range(300):
        is64 = p.rng.random() < 0.5
        rn = x if is64 else w
        d, n, m = p.reg(), p.reg(), p.reg()
        op = p.rng.choice(["adc", "adcs", "sbc", "sbcs", "ngc", "ngcs"])
        loads = {n: p.value(), m: p.value()}
        nzcv = p.rng.choice([0x0, 0x2, 0xF, 0xD])
        if op in ("ngc", "ngcs"):
            p.case([f"{op} {rn(d)}, {rn(m)}"], loads, nzcv)
        else:
            p.case([f"{op} {rn(d)}, {rn(n)}, {rn(m)}"], loads, nzcv)
    # C stays live across flag-neutral ADC/SBC and is consumed later in the
    # same block (dump reads NZCV only after a block exit).
    for _ in range(40):
        loads = {1: p.value(), 2: p.value()}
        nzcv = p.rng.choice([0x0, 0x2, 0xF, 0xD])
        p.case(["adc x3, x1, x2", "sbc w4, w1, w2", "cset x5, cs", "adc w6, w1, w2", "sbc x7, x1, x2",
                "csetm x8, hs", "adcs x9, x1, x2", "sbc x10, x2, x1", "adc x15, x1, x1", "cset x18, cs"], loads, nzcv)
    # XZR as the first operand (IR inline zero).
    for _ in range(20):
        loads = {2: p.value()}
        nzcv = p.rng.choice([0x0, 0x2, 0xF, 0xD])
        p.case(["adc x3, xzr, x2", "adc w4, wzr, w2", "sbc x5, xzr, x2", "sbc w7, wzr, w2", "cset x8, cs",
                "adcs x9, xzr, x2", "sbcs w10, wzr, w2"], loads, nzcv)


LOGIC_IMM32 = [0x1, 0xFF, 0xFFFF, 0x7FFFFFFF, 0x80000000, 0xF0F0F0F0, 0x55555555, 0xFFFFFFFE, 0x3C, 0xFFF0000F]
LOGIC_IMM64 = [0x1, 0xFF, 0xFFFF, 0x7FFFFFFF, 0x80000000, 0xF0F0F0F0F0F0F0F0, 0x5555555555555555, 0x3C, 0xFFFFFFFF, 0x8000000000000000, 0x00FF00FF00FF00FF, 0xFFFFFFFFFFFFFFFE, 0x7FFFFFFFFFFFFFFF,
                             0x0000FFFF0000FFFF, 0xFFFF000000000000]


def gen_logic(p):
    for _ in range(480):
        is64 = p.rng.random() < 0.6
        rn = x if is64 else w
        d, n, m = p.reg(), p.reg(), p.reg()
        loads = {n: p.value(), m: p.value(), d: p.value()}
        kind = p.rng.randrange(4)
        if kind == 0:
            op = p.rng.choice(["and", "orr", "eor", "ands"])
            imm = p.rng.choice(LOGIC_IMM64 if is64 else LOGIC_IMM32)
            p.case([f"{op} {rn(d)}, {rn(n)}, #0x{imm:x}"], loads)
        elif kind == 1:
            op = p.rng.choice(["and", "orr", "eor", "ands", "bic", "orn", "eon", "bics"])
            amt = p.rng.choice([0, 1, 13, 31] + ([32, 63] if is64 else []))
            sh = p.rng.choice(SHIFTS + ["ror"])
            p.case([f"{op} {rn(d)}, {rn(n)}, {rn(m)}, {sh} #{amt}"], loads)
        elif kind == 2:
            if p.rng.random() < 0.5:
                imm = p.rng.choice(LOGIC_IMM64 if is64 else LOGIC_IMM32)
                p.case([f"tst {rn(n)}, #0x{imm:x}"], loads)
            else:
                p.case([f"tst {rn(n)}, {rn(m)}"], loads)
        else:
            p.case([f"mvn {rn(d)}, {rn(m)}"], loads)
    # AND/ORR/EOR immediate into SP.
    for imm in [0xFFFFFFFFFFFFFFF0, 0xFFFFFFFFFFFFFF00]:
        p.case([f"mov x19, sp", f"and sp, x19, #0x{imm:x}", f"mov x20, sp", f"mov sp, x19"])


def gen_movewide(p):
    for _ in range(60):
        is64 = p.rng.random() < 0.6
        rn = x if is64 else w
        d = p.reg()
        loads = {d: p.value()}
        op = p.rng.choice(["movz", "movn", "movk"])
        imm = p.rng.getrandbits(16)
        hw = p.rng.choice([0, 16] + ([32, 48] if is64 else []))
        p.case([f"{op} {rn(d)}, #0x{imm:x}, lsl #{hw}"], loads)


def gen_bitfield(p):
    for _ in range(480):
        is64 = p.rng.random() < 0.6
        rn = x if is64 else w
        size = 64 if is64 else 32
        d, n = p.reg(), p.reg()
        loads = {n: p.value(), d: p.value()}
        kind = p.rng.randrange(6)
        if kind == 0:
            op = p.rng.choice(["sbfm", "bfm", "ubfm"])
            r, s = p.rng.randrange(size), p.rng.randrange(size)
            p.case([f"{op} {rn(d)}, {rn(n)}, #{r}, #{s}"], loads)
        elif kind == 1:
            op = p.rng.choice(["asr", "lsr", "lsl"])
            amt = p.rng.randrange(size)
            p.case([f"{op} {rn(d)}, {rn(n)}, #{amt}"], loads)
        elif kind == 2:
            op = p.rng.choice(["sbfiz", "sbfx", "ubfiz", "ubfx", "bfi", "bfxil"])
            lsb = p.rng.randrange(size)
            width = p.rng.randrange(1, size - lsb + 1)
            p.case([f"{op} {rn(d)}, {rn(n)}, #{lsb}, #{width}"], loads)
        elif kind == 3:
            op = p.rng.choice(["sxtb", "sxth", "uxtb", "uxth"])
            p.case([f"{op} {rn(d)}, {w(n)}"], loads)
        elif kind == 4:
            p.case([f"sxtw {x(d)}, {w(n)}"], loads)
        else:
            m = p.reg()
            loads[m] = p.value()
            lsb = p.rng.randrange(size)
            op = p.rng.choice(["extr", "ror"])
            if op == "extr":
                p.case([f"extr {rn(d)}, {rn(n)}, {rn(m)}, #{lsb}"], loads)
            else:
                p.case([f"ror {rn(d)}, {rn(n)}, #{lsb}"], loads)


def gen_shiftvar(p):
    amounts = [0, 1, 5, 31, 32, 33, 63, 64, 65, 127, 0xFFFFFFFF, 0x8000000000000001]
    for _ in range(240):
        is64 = p.rng.random() < 0.5
        rn = x if is64 else w
        d, n, m = p.distinct_regs(3)
        op = p.rng.choice(["lsl", "lsr", "asr", "ror"])
        p.case([f"{op} {rn(d)}, {rn(n)}, {rn(m)}"], {n: p.value(), m: p.rng.choice(amounts)})


def gen_bits(p):
    for _ in range(240):
        is64 = p.rng.random() < 0.5
        rn = x if is64 else w
        d, n = p.reg(), p.reg()
        ops = ["clz", "cls", "rbit", "rev", "rev16"] + (["rev32"] if is64 else [])
        op = p.rng.choice(ops)
        p.case([f"{op} {rn(d)}, {rn(n)}"], {n: p.value(), d: p.value()})


def gen_csel(p):
    for _ in range(360):
        is64 = p.rng.random() < 0.5
        rn = x if is64 else w
        d, n, m = p.reg(), p.reg(), p.reg()
        cond = p.rng.choice(CONDS)
        loads = {n: p.value(), m: p.value(), d: p.value()}
        kind = p.rng.randrange(4)
        if kind == 0:
            op = p.rng.choice(["csel", "csinc", "csinv", "csneg"])
            p.case([f"{op} {rn(d)}, {rn(n)}, {rn(m)}, {cond}"], loads, p.rng.randrange(16))
        elif kind == 1:
            if cond in ("al", "nv"):
                cond = "eq"
            op = p.rng.choice(["cset", "csetm"])
            p.case([f"{op} {rn(d)}, {cond}"], loads, p.rng.randrange(16))
        elif kind == 2:
            op = p.rng.choice(["ccmp", "ccmn"])
            imm = p.rng.choice([0, 1, 5, 31])
            nz = p.rng.randrange(16)
            p.case([f"{op} {rn(n)}, #{imm}, #{nz}, {cond}"], loads, p.rng.randrange(16))
        else:
            op = p.rng.choice(["ccmp", "ccmn"])
            nz = p.rng.randrange(16)
            p.case([f"{op} {rn(n)}, {rn(m)}, #{nz}, {cond}"], loads, p.rng.randrange(16))
    # CCMN with an immediate near INT64_MAX: exercises the V flag of the 64-bit path.
    for v in [0x7FFFFFFFFFFFFFFF, 0x7FFFFFFFFFFFFFF0, 0xFFFFFFFFFFFFFFFF, 0x7FFFFFFF]:
        for imm in [1, 15, 31]:
            p.case([f"ccmn x1, #{imm}, #0, eq"], {1: v}, 0x4)
            p.case([f"ccmn w1, #{imm}, #0, eq"], {1: v}, 0x4)


def gen_muldiv(p):
    for _ in range(300):
        is64 = p.rng.random() < 0.5
        rn = x if is64 else w
        d, n, m, a = p.reg(), p.reg(), p.reg(), p.reg()
        loads = {n: p.value(), m: p.value(), a: p.value()}
        op = p.rng.choice(["mul", "mneg", "madd", "msub", "smull", "umull", "smnegl", "umnegl",
                           "smaddl", "smsubl", "umaddl", "umsubl", "smulh", "umulh"])
        if op in ("mul", "mneg"):
            p.case([f"{op} {rn(d)}, {rn(n)}, {rn(m)}"], loads)
        elif op in ("madd", "msub"):
            p.case([f"{op} {rn(d)}, {rn(n)}, {rn(m)}, {rn(a)}"], loads)
        elif op in ("smull", "umull", "smnegl", "umnegl"):
            p.case([f"{op} {x(d)}, {w(n)}, {w(m)}"], loads)
        elif op in ("smulh", "umulh"):
            p.case([f"{op} {x(d)}, {x(n)}, {x(m)}"], loads)
        else:
            p.case([f"{op} {x(d)}, {w(n)}, {w(m)}, {x(a)}"], loads)
    divisors = [0, 1, 0xFFFFFFFFFFFFFFFF, 0xFFFFFFFF, 2, 7, 0x8000000000000000, 0x80000000]
    dividends = [0, 1, 0x8000000000000000, 0x80000000, 0x7FFFFFFFFFFFFFFF, 0xFFFFFFFFFFFFFFF9, 100, 0xFFFFFFFF80000000]
    for dv in dividends:
        for ds in divisors:
            for is64 in (True, False):
                rn = x if is64 else w
                for op in ("sdiv", "udiv"):
                    p.case([f"{op} {rn(3)}, {rn(1)}, {rn(2)}"], {1: dv, 2: ds})
    for _ in range(40):
        is64 = p.rng.random() < 0.5
        rn = x if is64 else w
        d, n, m = p.reg(), p.reg(), p.reg()
        op = p.rng.choice(["sdiv", "udiv"])
        p.case([f"{op} {rn(d)}, {rn(n)}, {rn(m)}"], {n: p.value(), m: p.value()})


def gen_branch(p):
    # Every condition against every NZCV value. X5 records the path taken.
    for cond in CONDS:
        for nzcv in range(16):
            p.case(["mov x5, #1", f"b.{cond} 2f", "mov x5, #2", "2:"], None, nzcv)
    for _ in range(40):
        is64 = p.rng.random() < 0.5
        rn = x if is64 else w
        r = p.reg()
        value = p.rng.choice([0, 1, 0x100000000, 0x80000000, p.value()])
        op = p.rng.choice(["cbz", "cbnz"])
        p.case(["mov x5, #1", f"{op} {rn(r)}, 2f", "mov x5, #2", "2:"], {r: value})
    for _ in range(60):
        r = p.reg()
        value = p.value()
        bit = p.rng.randrange(64)
        op = p.rng.choice(["tbz", "tbnz"])
        reg = x(r) if bit >= 32 or p.rng.random() < 0.5 else w(r)
        p.case(["mov x5, #1", f"{op} {reg}, #{bit}, 2f", "mov x5, #2", "2:"], {r: value})
    # Backwards branches and a short loop (branch to the block's own entry).
    p.case(["mov x5, #0", "mov x6, #10", "2: add x5, x5, x6", "subs x6, x6, #1", "b.ne 2b"])
    p.case(["mov x5, #0", "mov x6, #300", "2: add x5, x5, #3", "sub x6, x6, #1", "cbnz x6, 2b"])
    # BL / BLR / RET / BR.
    p.case(["mov x5, #0", "bl test_func", "mov x6, x30"])
    p.case(["adr x7, test_func", "blr x7", "mov x6, x30"])
    p.case(["adr x7, 2f", "br x7", "mov x5, #99", "2: mov x6, #7"])
    p.case(["adr x19, 2f", "mov x30, x19", "ret", "mov x5, #99", "2: mov x6, #8"])
    p.case(["adr x19, 2f", "ret x19", "mov x5, #99", "2: mov x6, #9"])
    p.emit("        b       3f")
    p.emit("test_func:")
    p.emit("        add     x5, x5, #0x55")
    p.emit("        ret")
    p.emit("3:")


def gen_adr(p):
    for off in ["buf", "stack_top", "_start", "dump", ".", ". + 0x80000", ". - 0x1000"]:
        p.case([f"adr x3, {off}", f"adrp x4, {off}"])


def gen_loadstore(p):
    # X19 points at buf+128. Operands stay inside buf.
    p.emit("        adrp    x19, buf")
    p.emit("        add     x19, x19, :lo12:buf")
    p.emit("        add     x19, x19, #128")
    sizes = [("b", "w", 1), ("h", "w", 2), ("", "w", 4), ("", "x", 8)]
    for _ in range(420):
        suffix, regtype, size = p.rng.choice(sizes)
        t = p.rng.choice([0, 1, 2, 9, 25])
        loads = {t: p.value()}
        kind = p.rng.randrange(6)
        is_load = p.rng.random() < 0.5
        base = "x19"
        if is_load:
            if size <= 2 and p.rng.random() < 0.5:
                op = "ldrs" + suffix
                regtype = p.rng.choice(["w", "x"])
            elif size == 4 and regtype == "w" and p.rng.random() < 0.3:
                op = "ldrsw"
                regtype = "x"
            else:
                op = "ldr" + suffix
        else:
            op = "str" + suffix
        rt = f"{regtype}{t}"
        if kind == 0:
            off = p.rng.randrange(0, 16) * size
            p.case([f"{op} {rt}, [{base}, #{off}]"], loads, dumpbuf=not is_load)
        elif kind == 1:
            off = p.rng.randrange(-32, 32)
            uop = op.replace("ldr", "ldur").replace("str", "stur")
            p.case([f"{uop} {rt}, [{base}, #{off}]"], loads, dumpbuf=not is_load)
        elif kind == 2:
            off = p.rng.randrange(-16, 16)
            p.case(["mov x20, x19", f"{op} {rt}, [x20, #{off}]!"], loads, dumpbuf=not is_load)
        elif kind == 3:
            off = p.rng.randrange(-16, 16)
            p.case(["mov x20, x19", f"{op} {rt}, [x20], #{off}"], loads, dumpbuf=not is_load)
        elif kind == 4:
            shift = size.bit_length() - 1
            ext = p.rng.choice(["uxtw", "sxtw", "lsl", "sxtx"])
            amount = p.rng.choice([0, shift])
            # Offsets stay within +-16 elements of buf+128. The high halves
            # of the W forms are garbage the extend must drop.
            if ext == "uxtw":
                idx = p.rng.choice([0, 1, 3, 0xABCD000000000002])
            elif ext == "sxtw":
                idx = p.rng.choice([0, 1, 0xFFFFFFFF, 0xFFFFFFFE, 0x12345678FFFFFFFC, 0x1_00000002])
            else:
                idx = p.rng.choice([0, 1, 3, 0xFFFFFFFFFFFFFFFF, 0xFFFFFFFFFFFFFFFC])
            idxreg = f"w10" if ext in ("uxtw", "sxtw") else "x10"
            loads[10] = idx
            if ext == "lsl" and amount == 0:
                p.case([f"{op} {rt}, [{base}, {idxreg}]"], loads, dumpbuf=not is_load)
            else:
                p.case([f"{op} {rt}, [{base}, {idxreg}, {ext} #{amount}]"], loads, dumpbuf=not is_load)
        else:
            u = p.rng.choice([r for r in (2, 3, 22, 28) if r != t])
            loads[u] = p.value()
            pt = regtype if not op.startswith("ldrs") else "x"
            psize = 8 if pt == "x" else 4
            off = p.rng.randrange(-4, 4) * psize
            mode = p.rng.randrange(3)
            if is_load and pt == "x" and p.rng.random() < 0.3:
                pair = "ldpsw"
                pt = "x"
                off = p.rng.randrange(-4, 4) * 4
            else:
                pair = "ldp" if is_load else "stp"
            rt1, rt2 = f"{pt}{t}", f"{pt}{u}"
            if mode == 0:
                p.case(["mov x20, x19", f"{pair} {rt1}, {rt2}, [x20, #{off}]"], loads, dumpbuf=not is_load)
            elif mode == 1:
                p.case(["mov x20, x19", f"{pair} {rt1}, {rt2}, [x20, #{off}]!"], loads, dumpbuf=not is_load)
            else:
                p.case(["mov x20, x19", f"{pair} {rt1}, {rt2}, [x20], #{off}"], loads, dumpbuf=not is_load)
    # Literal loads.
    p.case(["ldr x3, lit64", "ldr w4, lit32", "ldrsw x5, lit32", "prfm pldl1keep, lit64"])
    p.case(["mov x21, sp", "str x0, [sp, #-16]!", "ldr x1, [sp], #16", "stp x2, x3, [sp, #-32]!", "ldp x4, x5, [sp], #32"],
           {0: 0x1111, 2: 0x2222, 3: 0x3333})
    p.emit("        b       2f")
    p.emit("lit64:  .quad   0x8877665544332211")
    p.emit("lit32:  .word   0x80706050")
    p.emit("2:")


def gen_dczva(p):
    p.emit("        adrp    x19, buf")
    p.emit("        add     x19, x19, :lo12:buf")
    for off in [0, 64, 5, 70, 128, 191]:
        p.emit("        bl      reset_state")
        p.emit("        adrp    x19, buf")
        p.emit("        add     x19, x19, :lo12:buf")
        p.case([f"add x3, x19, #{off}", "dc zva, x3"], dumpbuf=True)


# Compare-and-branch fusion (IR/Passes/CompareBranchFusion.cpp). A compare's
# consumer may be rewritten into a direct compare of the operands, the compare
# itself dropped when nothing else reads its flags, and a compare recomputed
# on a branch leg that leaves the compile unit. Each of those is wrong in a
# data-dependent way if a case table entry is, so every condition is run after
# CMP/CMN/SUBS/ADDS at both sizes against immediates and registers (plain,
# shifted, extended, SP, ZR), on the signed, unsigned, carry and overflow
# boundaries, with W operands carrying garbage in bits 63:32. The flags are
# also read after the branch: by CSEL/CSET/CSINC/ADC/MRS/B.cond in the next
# block, across a far exit that leaves the unit (`far` code sits 8 KiB away,
# past the decoder's region window), and by the dump, and are killed before
# the dump in other cases so that the compare can be dropped.
CB_REGS = [0, 1, 2, 3, 4, 9, 10, 15, 18, 19, 22, 25, 28, 29]
CB_CONDS = CONDS[:14]
CB_EDGE_W = [0, 1, 2, 0x7FFFFFFE, 0x7FFFFFFF, 0x80000000, 0x80000001, 0xFFFFFFFE, 0xFFFFFFFF]
CB_EDGE_X = [0, 1, 2, 0x7FFFFFFFFFFFFFFE, 0x7FFFFFFFFFFFFFFF, 0x8000000000000000, 0x8000000000000001,
             0xFFFFFFFFFFFFFFFE, 0xFFFFFFFFFFFFFFFF, 0x7FFFFFFF, 0x80000000, 0xFFFFFFFF, 0x100000000]
CB_IMMS = [(0, 0), (1, 0), (2, 0), (0x7FF, 0), (0x800, 0), (0xFFF, 0), (1, 12), (0xFFF, 12)]


class CmpBranch:
    def __init__(self, p):
        self.p = p
        self.rng = p.rng
        self.far = 0

    def dirty(self, v, is64):
        """A W operand with garbage above bit 31 half the time."""
        v &= (1 << 64) - 1 if is64 else 0xFFFFFFFF
        if not is64 and self.rng.random() < 0.5:
            v |= self.rng.getrandbits(32) << 32
        return v

    def imm_values(self, c, is64, add):
        """Operand values on the boundaries of `a - c` (or `a + c` for add)."""
        bits = 64 if is64 else 32
        mask = (1 << bits) - 1
        smax = (1 << (bits - 1)) - 1
        smin = 1 << (bits - 1)
        if add:
            vals = [-c, -c - 1, -c + 1, smax - c, smax - c + 1, 0, mask, smin]
        else:
            vals = [c - 1, c, c + 1, 0, smax, smin, smin + c - 1, smin + c, mask]
        vals.append(self.rng.getrandbits(bits))
        return [v & mask for v in vals]

    def operand_pair(self, is64):
        edge = CB_EDGE_X if is64 else CB_EDGE_W
        r = self.rng.random()
        if r < 0.6:
            return self.rng.choice(edge), self.rng.choice(edge)
        if r < 0.8:
            v = self.rng.choice(edge + [self.p.value()])
            return v, v
        return self.p.value(), self.p.value()

    def compare(self, is64=None, kind=None):
        """A random flag-setting compare: (instruction, {reg: value})."""
        rng = self.rng
        if is64 is None:
            is64 = rng.random() < 0.5
        rn = x if is64 else w
        n, m, d = rng.sample(CB_REGS, 3)
        if kind is None:
            kind = rng.choice(["cmp_imm", "cmn_imm", "cmp_reg", "cmn_reg", "cmp_shift", "cmp_ext", "cmn_ext",
                               "subs_imm", "adds_imm", "subs_reg", "adds_reg", "subs_self", "cmp_sp", "cmp_zr", "tst"])
        if kind in ("cmp_imm", "cmn_imm", "subs_imm", "adds_imm", "subs_self"):
            imm, sh = rng.choice(CB_IMMS)
            add = kind in ("cmn_imm", "adds_imm")
            a = rng.choice(self.imm_values(imm << sh, is64, add))
            shs = f", lsl #{sh}" if sh else ""
            if kind in ("cmp_imm", "cmn_imm"):
                return f"{kind[:3]} {rn(n)}, #{imm}{shs}", {n: self.dirty(a, is64)}
            if kind == "subs_self":
                return f"subs {rn(n)}, {rn(n)}, #{imm}{shs}", {n: self.dirty(a, is64)}
            return f"{kind[:4]} {rn(d)}, {rn(n)}, #{imm}{shs}", {n: self.dirty(a, is64), d: self.p.value()}
        a, b = self.operand_pair(is64)
        loads = {n: self.dirty(a, is64), m: self.dirty(b, is64)}
        if kind in ("cmp_reg", "cmn_reg"):
            return f"{kind[:3]} {rn(n)}, {rn(m)}", loads
        if kind in ("subs_reg", "adds_reg"):
            loads[d] = self.p.value()
            return f"{kind[:4]} {rn(d)}, {rn(n)}, {rn(m)}", loads
        if kind == "cmp_shift":
            amt = rng.choice([1, 3, 31] + ([32, 63] if is64 else []))
            return f"cmp {rn(n)}, {rn(m)}, {rng.choice(SHIFTS)} #{amt}", loads
        if kind in ("cmp_ext", "cmn_ext"):
            ext = rng.choice(EXTENDS)
            src = x(m) if is64 and ext in ("uxtx", "sxtx") else w(m)
            return f"{kind[:3]} {rn(n)}, {src}, {ext} #{rng.randrange(5)}", loads
        if kind == "cmp_sp":
            # SP is the private static stack: the same value on both machines.
            if rng.random() < 0.5:
                return f"cmp {'sp' if is64 else 'wsp'}, #{rng.choice([0, 16, 0xFFF])}", {}
            return f"cmp {'sp' if is64 else 'wsp'}, {w(m)}, uxtw #{rng.randrange(5)}", {m: rng.getrandbits(12)}
        if kind == "cmp_zr":
            # A zero register on either side: the Src1 form is not fusable, the
            # Src2 form compares against zero (MI/PL fuse there).
            if rng.random() < 0.5:
                return f"cmp {rn(n)}, {'xzr' if is64 else 'wzr'}", loads
            return f"cmp {'xzr' if is64 else 'wzr'}, {rn(m)}", loads
        return f"tst {rn(n)}, {rn(m)}", loads

    def far_block(self, body):
        """Code in .text.far, out of reach of the decoder's region window."""
        self.p.emit("        .pushsection .text.far, \"ax\"")
        if self.far == 0:
            self.p.emit("        .skip   8192")
        self.far += 1
        for line in body:
            self.p.emit(f"{line}")
        self.p.emit("        .popsection")

    def cond(self):
        return self.rng.choice(CB_CONDS)

    def consumers(self, n, m):
        """NZCV readers after a branch, results into x6-x8, x11, x12."""
        c = [self.cond() for _ in range(4)]
        return [f"cset x6, {c[0]}", f"csinc x7, {x(n)}, {x(m)}, {c[1]}", f"adc x8, {x(n)}, {x(m)}",
                "mrs x12, nzcv", f"b.{c[2]} 8f", "mov x11, #3", "8:"]


def gen_cmpbranch(p):
    cb = CmpBranch(p)
    rng = p.rng

    def chain(ins, loads):
        # Every condition, each fused (or not) against its own copy of the
        # compare; the next copy kills the previous one's flags. X5 collects
        # one bit per condition, set when the branch falls through.
        body = ["mov x5, #0"]
        for i, c in enumerate(CB_CONDS):
            body += [ins, f"b.{c} 7f", f"orr x5, x5, #{1 << i}", "7:"]
        p.case(body, loads, desc=f"{ins} ; b.<each condition>, x5 = fall-through mask")

    # Immediates on every boundary, both sizes, CMP and CMN.
    for is64 in (False, True):
        rn = x if is64 else w
        for op in ("cmp", "cmn"):
            for imm, sh in CB_IMMS:
                for a in cb.imm_values(imm << sh, is64, op == "cmn"):
                    n = rng.choice(CB_REGS)
                    shs = f", lsl #{sh}" if sh else ""
                    chain(f"{op} {rn(n)}, #{imm}{shs}", {n: cb.dirty(a, is64)})
    # Register operands: every edge pair, both sizes, CMP and CMN.
    for is64 in (False, True):
        rn = x if is64 else w
        edge = CB_EDGE_X if is64 else CB_EDGE_W
        for op in ("cmp", "cmn"):
            for a in edge:
                for b in edge:
                    n, m = rng.sample(CB_REGS, 2)
                    chain(f"{op} {rn(n)}, {rn(m)}", {n: cb.dirty(a, is64), m: cb.dirty(b, is64)})
    # Every other compare form.
    for _ in range(160):
        chain(*cb.compare())

    # A branch within the unit, the flags then read in the next block.
    for _ in range(300):
        ins, loads = cb.compare()
        n, m = rng.sample(CB_REGS, 2)
        p.case(["mov x5, #1", ins, f"b.{cb.cond()} 7f", "mov x5, #2", "7:"] + cb.consumers(n, m), loads)

    # A branch that leaves the unit: its leg recomputes the flags, read at the
    # far target; the fall-through kills them (so the compare can go) or not.
    for i in range(300):
        ins, loads = cb.compare()
        n, m = rng.sample(CB_REGS, 2)
        kill = ["cmp x5, #0x33"] if rng.random() < 0.5 else []
        body = ["mov x5, #1", ins, f"b.{cb.cond()} far{i}", "mov x5, #2"] + kill + [f"back{i}:"]
        p.case(body, loads)
        cb.far_block([f"far{i}:", "        mov x5, #3"] + [f"        {l}" for l in cb.consumers(n, m)] + [f"        b back{i}"])

    # The same with the unit exit on the fall-through leg.
    for i in range(300, 380):
        ins, loads = cb.compare()
        n, m = rng.sample(CB_REGS, 2)
        body = ["mov x5, #1", ins, f"b.{cb.cond()} 7f", f"b far{i}", "7: mov x5, #2", "cmp x5, #0x44", f"back{i}:"]
        p.case(body, loads)
        cb.far_block([f"far{i}:", "        mov x5, #3"] + [f"        {l}" for l in cb.consumers(n, m)] + [f"        b back{i}"])

    # Selects in the compare's own block, then a branch or a kill.
    for _ in range(300):
        ins, loads = cb.compare()
        n, m = rng.sample(CB_REGS, 2)
        c = [cb.cond() for _ in range(5)]
        body = [ins, f"csel x6, {x(n)}, {x(m)}, {c[0]}", f"cset w7, {c[1]}", f"csinv x8, {x(n)}, {x(m)}, {c[2]}",
                f"csneg w11, {w(n)}, {w(m)}, {c[3]}", f"csetm x12, {c[4]}"]
        tail = rng.randrange(3)
        if tail == 0:
            body += [f"b.{cb.cond()} 7f", "mov x5, #9", "7:"]
        elif tail == 1:
            body += ["cmn x6, #1"]
        p.case(body, loads)

    # Loops: the compare and its branch on the back edge.
    loops = [
        ("subs w7, w7, #1", "ne", 0xDEAD000000000006),
        ("cmp x7, #3", "gt", 12),
        ("cmp w7, #0x7FE", "hi", 0x802),
        ("cmp x7, #0", "ge", 4),
        ("cmn x7, #3", "lt", 0xFFFFFFFFFFFFFFF6),
        ("cmn w7, #1", "ne", 0xFFFFFFF8),
        ("cmp w7, w9", "ls", 0x7FFFFFF8),
        ("cmp x7, x9", "lo", 0xFFFFFFFFFFFFFFF0),
        ("cmp w7, #0", "pl", 0x7),
        ("cmp w7, #1", "cs", 0x80000005),
    ]
    for ins, cond, start in loops:
        step = "add" if cond in ("lt", "ne") and ins.startswith("cmn") else "sub"
        if ins.startswith("cmp w7, w9") or ins.startswith("cmp x7, x9"):
            step = "add"
        upd = [] if ins.startswith("subs") else [f"{step} x7, x7, #1"]
        body = ["mov x6, #0", "7: add x6, x6, #1"] + upd + [ins, f"b.{cond} 7b"]
        p.case(body, {7: start, 9: 0x7FFFFFFC if "w9" in ins else 0xFFFFFFFFFFFFFFF8})


GROUPS = {
    "addsub": gen_addsub,
    "adc": gen_adc,
    "logic": gen_logic,
    "movewide": gen_movewide,
    "bitfield": gen_bitfield,
    "shiftvar": gen_shiftvar,
    "bits": gen_bits,
    "csel": gen_csel,
    "muldiv": gen_muldiv,
    "branch": gen_branch,
    "adr": gen_adr,
    "loadstore": gen_loadstore,
    "dczva": gen_dczva,
    "cmpbranch": gen_cmpbranch,
}


def main():
    outdir = sys.argv[1]
    os.makedirs(outdir, exist_ok=True)
    for name, fn in GROUPS.items():
        rng = random.Random(f"{SEED}-{name}")
        p = Program(name, rng)
        fn(p)
        p.write(outdir)
        print(f"{name}: {p.cases} cases")


if __name__ == "__main__":
    main()
