#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Generates the differential A64Frontend test programs.

Each generated program is a list of cases. A case loads operands into
registers (LDR literal), sets NZCV (MSR), runs one instruction or a short
sequence, and calls `dump` (common.S), which prints every GPR, SP and NZCV.
The Pi's output is the golden; POWERarm's output must match it byte for byte.

Inputs are an edge-case corpus plus seeded random values, so a rerun
generates identical programs.

Usage: gen.py OUTDIR
"""

import os
import random
import sys

SEED = 0x41363446

EDGE64 = [
    0, 1, 2, 0x7F, 0x80, 0xFF, 0x7FFF, 0x8000, 0xFFFF,
    0x7FFFFFFF, 0x80000000, 0xFFFFFFFF, 0x100000000, 0x17FFFFFFF,
    0x7FFFFFFFFFFFFFFF, 0x8000000000000000, 0xFFFFFFFFFFFFFFFF,
    0xFFFFFFFFFFFFFFFE, 0xFFFFFFFF80000000, 0x00000000FFFFFFFE,
    0x123456789ABCDEF0, 0xFEDCBA9876543210, 0xDEADBEEF00000001,
]

# Registers a case may use for operands and results. A mix of statically
# allocated guest registers (X0-X8, X19-X24, X29) and context-backed ones
# (X9-X18, X25-X28). X30 is left alone: `bl dump` writes it.
REGS = [0, 1, 2, 3, 4, 7, 8, 9, 10, 15, 18, 19, 22, 25, 28, 29]

NZCV_VALUES = [0x0, 0x2, 0x4, 0x6, 0x8, 0x9, 0xA, 0xF, 0x1, 0x5, 0xC, 0x3]

CONDS = ["eq", "ne", "cs", "cc", "mi", "pl", "vs", "vc", "hi", "ls", "ge", "lt", "gt", "le", "al", "nv"]

SHIFTS = ["lsl", "lsr", "asr"]
EXTENDS = ["uxtb", "uxth", "uxtw", "uxtx", "sxtb", "sxth", "sxtw", "sxtx"]


class Program:
    def __init__(self, name, rng):
        self.name = name
        self.rng = rng
        self.lines = []
        self.cases = 0

    def emit(self, text):
        self.lines.append(text)

    def value(self):
        r = self.rng.random()
        if r < 0.45:
            return self.rng.choice(EDGE64)
        if r < 0.6:
            return self.rng.getrandbits(8)
        if r < 0.75:
            return self.rng.getrandbits(32)
        return self.rng.getrandbits(64)

    def reg(self):
        return self.rng.choice(REGS)

    def distinct_regs(self, n):
        return self.rng.sample(REGS, n)

    def load(self, reg, value):
        self.emit(f"        ldr     x{reg}, =0x{value & 0xFFFFFFFFFFFFFFFF:x}")

    def flags(self, nzcv=None):
        if nzcv is None:
            nzcv = self.rng.choice(NZCV_VALUES)
        self.emit(f"        mov     x17, #0x{nzcv << 28:x}")
        self.emit("        msr     nzcv, x17")

    def case(self, body, loads=None, nzcv=None, dumpbuf=False):
        """body: list of instruction lines. loads: {reg: value}."""
        self.cases += 1
        self.emit(f"        // case {self.cases}: {' ; '.join(body)}")
        for reg, value in (loads or {}).items():
            self.load(reg, value)
        self.flags(nzcv)
        for line in body:
            self.emit(f"        {line}")
        self.emit("        bl      dump")
        if dumpbuf:
            self.emit("        bl      dumpbuf")
        if self.cases % 16 == 0:
            self.emit("        b       1f")
            self.emit("        .ltorg")
            self.emit("1:")

    def write(self, outdir):
        path = os.path.join(outdir, f"{self.name}.S")
        with open(path, "w") as f:
            f.write(f"// Generated by gen.py (seed 0x{SEED:x}). Do not edit.\n")
            f.write('#include "common.S"\n')
            f.write("        test_start\n")
            f.write("\n".join(self.lines))
            f.write("\n        test_exit\n        .ltorg\n")


def w(reg):
    return f"w{reg}"


def x(reg):
    return f"x{reg}"


def gen_addsub(p):
    for _ in range(480):
        is64 = p.rng.random() < 0.6
        rn = x if is64 else w
        d, n, m = p.reg(), p.reg(), p.reg()
        loads = {n: p.value(), m: p.value()}
        kind = p.rng.randrange(6)
        op = p.rng.choice(["add", "adds", "sub", "subs"])
        if kind == 0:
            imm = p.rng.choice([0, 1, 4095, p.rng.randrange(4096)])
            sh = p.rng.choice(["", ", lsl #12"])
            p.case([f"{op} {rn(d)}, {rn(n)}, #{imm}{sh}"], loads)
        elif kind == 1:
            amt = p.rng.choice([0, 1, 7, 31] + ([32, 63] if is64 else []))
            sh = p.rng.choice(SHIFTS)
            p.case([f"{op} {rn(d)}, {rn(n)}, {rn(m)}, {sh} #{amt}"], loads)
        elif kind == 2:
            ext = p.rng.choice(EXTENDS)
            amt = p.rng.randrange(5)
            src = x(m) if ext in ("uxtx", "sxtx") else w(m)
            if not is64:
                src = w(m)
            p.case([f"{op} {rn(d)}, {rn(n)}, {src}, {ext} #{amt}"], loads)
        elif kind == 3:
            cmp = p.rng.choice(["cmp", "cmn"])
            if p.rng.random() < 0.5:
                imm = p.rng.choice([0, 1, 31, 4095, p.rng.randrange(4096)])
                p.case([f"{cmp} {rn(n)}, #{imm}"], loads)
            else:
                p.case([f"{cmp} {rn(n)}, {rn(m)}"], loads)
        elif kind == 4:
            neg = p.rng.choice(["neg", "negs"])
            p.case([f"{neg} {rn(d)}, {rn(m)}"], loads)
        else:
            # SP as base and destination. SP is a static stack here, so its
            # value prints the same on both machines.
            imm = p.rng.choice([0, 8, 16, 4095])
            if is64:
                p.case([f"sub sp, sp, #{imm}", f"add {x(d)}, sp, #{imm}", f"add sp, sp, #{imm}"], loads)
            else:
                p.case([f"add {w(d)}, wsp, #{imm}"], loads)
    # Extended register with SP: add sp/xN, sp, wM, uxtw #s.
    for _ in range(20):
        d, m = p.reg(), p.reg()
        ext = p.rng.choice(["uxtw", "sxtw", "uxtb", "sxth", "lsl"])
        amt = p.rng.randrange(5)
        src = x(m) if ext == "lsl" else w(m)
        p.case([f"add {x(d)}, sp, {src}, {ext} #{amt}", f"cmp sp, {src}, {ext} #{amt}"], {m: p.rng.getrandbits(12)})


def gen_adc(p):
    for _ in range(300):
        is64 = p.rng.random() < 0.5
        rn = x if is64 else w
        d, n, m = p.reg(), p.reg(), p.reg()
        op = p.rng.choice(["adc", "adcs", "sbc", "sbcs", "ngc", "ngcs"])
        loads = {n: p.value(), m: p.value()}
        nzcv = p.rng.choice([0x0, 0x2, 0xF, 0xD])
        if op in ("ngc", "ngcs"):
            p.case([f"{op} {rn(d)}, {rn(m)}"], loads, nzcv)
        else:
            p.case([f"{op} {rn(d)}, {rn(n)}, {rn(m)}"], loads, nzcv)


LOGIC_IMM32 = [0x1, 0xFF, 0xFFFF, 0x7FFFFFFF, 0x80000000, 0xF0F0F0F0, 0x55555555, 0xFFFFFFFE, 0x3C, 0xFFF0000F]
LOGIC_IMM64 = [0x1, 0xFF, 0xFFFF, 0x7FFFFFFF, 0x80000000, 0xF0F0F0F0F0F0F0F0, 0x5555555555555555, 0x3C, 0xFFFFFFFF, 0x8000000000000000, 0x00FF00FF00FF00FF, 0xFFFFFFFFFFFFFFFE, 0x7FFFFFFFFFFFFFFF,
                             0x0000FFFF0000FFFF, 0xFFFF000000000000]


def gen_logic(p):
    for _ in range(480):
        is64 = p.rng.random() < 0.6
        rn = x if is64 else w
        d, n, m = p.reg(), p.reg(), p.reg()
        loads = {n: p.value(), m: p.value(), d: p.value()}
        kind = p.rng.randrange(4)
        if kind == 0:
            op = p.rng.choice(["and", "orr", "eor", "ands"])
            imm = p.rng.choice(LOGIC_IMM64 if is64 else LOGIC_IMM32)
            p.case([f"{op} {rn(d)}, {rn(n)}, #0x{imm:x}"], loads)
        elif kind == 1:
            op = p.rng.choice(["and", "orr", "eor", "ands", "bic", "orn", "eon", "bics"])
            amt = p.rng.choice([0, 1, 13, 31] + ([32, 63] if is64 else []))
            sh = p.rng.choice(SHIFTS + ["ror"])
            p.case([f"{op} {rn(d)}, {rn(n)}, {rn(m)}, {sh} #{amt}"], loads)
        elif kind == 2:
            if p.rng.random() < 0.5:
                imm = p.rng.choice(LOGIC_IMM64 if is64 else LOGIC_IMM32)
                p.case([f"tst {rn(n)}, #0x{imm:x}"], loads)
            else:
                p.case([f"tst {rn(n)}, {rn(m)}"], loads)
        else:
            p.case([f"mvn {rn(d)}, {rn(m)}"], loads)
    # AND/ORR/EOR immediate into SP.
    for imm in [0xFFFFFFFFFFFFFFF0, 0xFFFFFFFFFFFFFF00]:
        p.case([f"mov x19, sp", f"and sp, x19, #0x{imm:x}", f"mov x20, sp", f"mov sp, x19"])


def gen_movewide(p):
    for _ in range(60):
        is64 = p.rng.random() < 0.6
        rn = x if is64 else w
        d = p.reg()
        loads = {d: p.value()}
        op = p.rng.choice(["movz", "movn", "movk"])
        imm = p.rng.getrandbits(16)
        hw = p.rng.choice([0, 16] + ([32, 48] if is64 else []))
        p.case([f"{op} {rn(d)}, #0x{imm:x}, lsl #{hw}"], loads)


def gen_bitfield(p):
    for _ in range(480):
        is64 = p.rng.random() < 0.6
        rn = x if is64 else w
        size = 64 if is64 else 32
        d, n = p.reg(), p.reg()
        loads = {n: p.value(), d: p.value()}
        kind = p.rng.randrange(6)
        if kind == 0:
            op = p.rng.choice(["sbfm", "bfm", "ubfm"])
            r, s = p.rng.randrange(size), p.rng.randrange(size)
            p.case([f"{op} {rn(d)}, {rn(n)}, #{r}, #{s}"], loads)
        elif kind == 1:
            op = p.rng.choice(["asr", "lsr", "lsl"])
            amt = p.rng.randrange(size)
            p.case([f"{op} {rn(d)}, {rn(n)}, #{amt}"], loads)
        elif kind == 2:
            op = p.rng.choice(["sbfiz", "sbfx", "ubfiz", "ubfx", "bfi", "bfxil"])
            lsb = p.rng.randrange(size)
            width = p.rng.randrange(1, size - lsb + 1)
            p.case([f"{op} {rn(d)}, {rn(n)}, #{lsb}, #{width}"], loads)
        elif kind == 3:
            op = p.rng.choice(["sxtb", "sxth", "uxtb", "uxth"])
            p.case([f"{op} {rn(d)}, {w(n)}"], loads)
        elif kind == 4:
            p.case([f"sxtw {x(d)}, {w(n)}"], loads)
        else:
            m = p.reg()
            loads[m] = p.value()
            lsb = p.rng.randrange(size)
            op = p.rng.choice(["extr", "ror"])
            if op == "extr":
                p.case([f"extr {rn(d)}, {rn(n)}, {rn(m)}, #{lsb}"], loads)
            else:
                p.case([f"ror {rn(d)}, {rn(n)}, #{lsb}"], loads)


def gen_shiftvar(p):
    amounts = [0, 1, 5, 31, 32, 33, 63, 64, 65, 127, 0xFFFFFFFF, 0x8000000000000001]
    for _ in range(240):
        is64 = p.rng.random() < 0.5
        rn = x if is64 else w
        d, n, m = p.distinct_regs(3)
        op = p.rng.choice(["lsl", "lsr", "asr", "ror"])
        p.case([f"{op} {rn(d)}, {rn(n)}, {rn(m)}"], {n: p.value(), m: p.rng.choice(amounts)})


def gen_bits(p):
    for _ in range(240):
        is64 = p.rng.random() < 0.5
        rn = x if is64 else w
        d, n = p.reg(), p.reg()
        ops = ["clz", "cls", "rbit", "rev", "rev16"] + (["rev32"] if is64 else [])
        op = p.rng.choice(ops)
        p.case([f"{op} {rn(d)}, {rn(n)}"], {n: p.value(), d: p.value()})


def gen_csel(p):
    for _ in range(360):
        is64 = p.rng.random() < 0.5
        rn = x if is64 else w
        d, n, m = p.reg(), p.reg(), p.reg()
        cond = p.rng.choice(CONDS)
        loads = {n: p.value(), m: p.value(), d: p.value()}
        kind = p.rng.randrange(4)
        if kind == 0:
            op = p.rng.choice(["csel", "csinc", "csinv", "csneg"])
            p.case([f"{op} {rn(d)}, {rn(n)}, {rn(m)}, {cond}"], loads, p.rng.randrange(16))
        elif kind == 1:
            if cond in ("al", "nv"):
                cond = "eq"
            op = p.rng.choice(["cset", "csetm"])
            p.case([f"{op} {rn(d)}, {cond}"], loads, p.rng.randrange(16))
        elif kind == 2:
            op = p.rng.choice(["ccmp", "ccmn"])
            imm = p.rng.choice([0, 1, 5, 31])
            nz = p.rng.randrange(16)
            p.case([f"{op} {rn(n)}, #{imm}, #{nz}, {cond}"], loads, p.rng.randrange(16))
        else:
            op = p.rng.choice(["ccmp", "ccmn"])
            nz = p.rng.randrange(16)
            p.case([f"{op} {rn(n)}, {rn(m)}, #{nz}, {cond}"], loads, p.rng.randrange(16))
    # CCMN with an immediate near INT64_MAX: exercises the V flag of the 64-bit path.
    for v in [0x7FFFFFFFFFFFFFFF, 0x7FFFFFFFFFFFFFF0, 0xFFFFFFFFFFFFFFFF, 0x7FFFFFFF]:
        for imm in [1, 15, 31]:
            p.case([f"ccmn x1, #{imm}, #0, eq"], {1: v}, 0x4)
            p.case([f"ccmn w1, #{imm}, #0, eq"], {1: v}, 0x4)


def gen_muldiv(p):
    for _ in range(300):
        is64 = p.rng.random() < 0.5
        rn = x if is64 else w
        d, n, m, a = p.reg(), p.reg(), p.reg(), p.reg()
        loads = {n: p.value(), m: p.value(), a: p.value()}
        op = p.rng.choice(["mul", "mneg", "madd", "msub", "smull", "umull", "smnegl", "umnegl",
                           "smaddl", "smsubl", "umaddl", "umsubl", "smulh", "umulh"])
        if op in ("mul", "mneg"):
            p.case([f"{op} {rn(d)}, {rn(n)}, {rn(m)}"], loads)
        elif op in ("madd", "msub"):
            p.case([f"{op} {rn(d)}, {rn(n)}, {rn(m)}, {rn(a)}"], loads)
        elif op in ("smull", "umull", "smnegl", "umnegl"):
            p.case([f"{op} {x(d)}, {w(n)}, {w(m)}"], loads)
        elif op in ("smulh", "umulh"):
            p.case([f"{op} {x(d)}, {x(n)}, {x(m)}"], loads)
        else:
            p.case([f"{op} {x(d)}, {w(n)}, {w(m)}, {x(a)}"], loads)
    divisors = [0, 1, 0xFFFFFFFFFFFFFFFF, 0xFFFFFFFF, 2, 7, 0x8000000000000000, 0x80000000]
    dividends = [0, 1, 0x8000000000000000, 0x80000000, 0x7FFFFFFFFFFFFFFF, 0xFFFFFFFFFFFFFFF9, 100, 0xFFFFFFFF80000000]
    for dv in dividends:
        for ds in divisors:
            for is64 in (True, False):
                rn = x if is64 else w
                for op in ("sdiv", "udiv"):
                    p.case([f"{op} {rn(3)}, {rn(1)}, {rn(2)}"], {1: dv, 2: ds})
    for _ in range(40):
        is64 = p.rng.random() < 0.5
        rn = x if is64 else w
        d, n, m = p.reg(), p.reg(), p.reg()
        op = p.rng.choice(["sdiv", "udiv"])
        p.case([f"{op} {rn(d)}, {rn(n)}, {rn(m)}"], {n: p.value(), m: p.value()})


def gen_branch(p):
    # Every condition against every NZCV value. X5 records the path taken.
    for cond in CONDS:
        for nzcv in range(16):
            p.case(["mov x5, #1", f"b.{cond} 2f", "mov x5, #2", "2:"], None, nzcv)
    for _ in range(40):
        is64 = p.rng.random() < 0.5
        rn = x if is64 else w
        r = p.reg()
        value = p.rng.choice([0, 1, 0x100000000, 0x80000000, p.value()])
        op = p.rng.choice(["cbz", "cbnz"])
        p.case(["mov x5, #1", f"{op} {rn(r)}, 2f", "mov x5, #2", "2:"], {r: value})
    for _ in range(60):
        r = p.reg()
        value = p.value()
        bit = p.rng.randrange(64)
        op = p.rng.choice(["tbz", "tbnz"])
        reg = x(r) if bit >= 32 or p.rng.random() < 0.5 else w(r)
        p.case(["mov x5, #1", f"{op} {reg}, #{bit}, 2f", "mov x5, #2", "2:"], {r: value})
    # Backwards branches and a short loop (branch to the block's own entry).
    p.case(["mov x5, #0", "mov x6, #10", "2: add x5, x5, x6", "subs x6, x6, #1", "b.ne 2b"])
    p.case(["mov x5, #0", "mov x6, #300", "2: add x5, x5, #3", "sub x6, x6, #1", "cbnz x6, 2b"])
    # BL / BLR / RET / BR.
    p.case(["mov x5, #0", "bl test_func", "mov x6, x30"])
    p.case(["adr x7, test_func", "blr x7", "mov x6, x30"])
    p.case(["adr x7, 2f", "br x7", "mov x5, #99", "2: mov x6, #7"])
    p.case(["adr x19, 2f", "mov x30, x19", "ret", "mov x5, #99", "2: mov x6, #8"])
    p.case(["adr x19, 2f", "ret x19", "mov x5, #99", "2: mov x6, #9"])
    p.emit("        b       3f")
    p.emit("test_func:")
    p.emit("        add     x5, x5, #0x55")
    p.emit("        ret")
    p.emit("3:")


def gen_adr(p):
    for off in ["buf", "stack_top", "_start", "dump", ".", ". + 0x80000", ". - 0x1000"]:
        p.case([f"adr x3, {off}", f"adrp x4, {off}"])


def gen_loadstore(p):
    # X19 points at buf+128. Operands stay inside buf.
    p.emit("        adrp    x19, buf")
    p.emit("        add     x19, x19, :lo12:buf")
    p.emit("        add     x19, x19, #128")
    sizes = [("b", "w", 1), ("h", "w", 2), ("", "w", 4), ("", "x", 8)]
    for _ in range(420):
        suffix, regtype, size = p.rng.choice(sizes)
        t = p.rng.choice([0, 1, 2, 9, 25])
        loads = {t: p.value()}
        kind = p.rng.randrange(6)
        is_load = p.rng.random() < 0.5
        base = "x19"
        if is_load:
            if size <= 2 and p.rng.random() < 0.5:
                op = "ldrs" + suffix
                regtype = p.rng.choice(["w", "x"])
            elif size == 4 and regtype == "w" and p.rng.random() < 0.3:
                op = "ldrsw"
                regtype = "x"
            else:
                op = "ldr" + suffix
        else:
            op = "str" + suffix
        rt = f"{regtype}{t}"
        if kind == 0:
            off = p.rng.randrange(0, 16) * size
            p.case([f"{op} {rt}, [{base}, #{off}]"], loads, dumpbuf=not is_load)
        elif kind == 1:
            off = p.rng.randrange(-32, 32)
            uop = op.replace("ldr", "ldur").replace("str", "stur")
            p.case([f"{uop} {rt}, [{base}, #{off}]"], loads, dumpbuf=not is_load)
        elif kind == 2:
            off = p.rng.randrange(-16, 16)
            p.case(["mov x20, x19", f"{op} {rt}, [x20, #{off}]!"], loads, dumpbuf=not is_load)
        elif kind == 3:
            off = p.rng.randrange(-16, 16)
            p.case(["mov x20, x19", f"{op} {rt}, [x20], #{off}"], loads, dumpbuf=not is_load)
        elif kind == 4:
            shift = size.bit_length() - 1
            ext = p.rng.choice(["uxtw", "sxtw", "lsl", "sxtx"])
            amount = p.rng.choice([0, shift])
            # Offsets stay within +-16 elements of buf+128. The high halves
            # of the W forms are garbage the extend must drop.
            if ext == "uxtw":
                idx = p.rng.choice([0, 1, 3, 0xABCD000000000002])
            elif ext == "sxtw":
                idx = p.rng.choice([0, 1, 0xFFFFFFFF, 0xFFFFFFFE, 0x12345678FFFFFFFC, 0x1_00000002])
            else:
                idx = p.rng.choice([0, 1, 3, 0xFFFFFFFFFFFFFFFF, 0xFFFFFFFFFFFFFFFC])
            idxreg = f"w10" if ext in ("uxtw", "sxtw") else "x10"
            loads[10] = idx
            if ext == "lsl" and amount == 0:
                p.case([f"{op} {rt}, [{base}, {idxreg}]"], loads, dumpbuf=not is_load)
            else:
                p.case([f"{op} {rt}, [{base}, {idxreg}, {ext} #{amount}]"], loads, dumpbuf=not is_load)
        else:
            u = p.rng.choice([r for r in (2, 3, 22, 28) if r != t])
            loads[u] = p.value()
            pt = regtype if not op.startswith("ldrs") else "x"
            psize = 8 if pt == "x" else 4
            off = p.rng.randrange(-4, 4) * psize
            mode = p.rng.randrange(3)
            if is_load and pt == "x" and p.rng.random() < 0.3:
                pair = "ldpsw"
                pt = "x"
                off = p.rng.randrange(-4, 4) * 4
            else:
                pair = "ldp" if is_load else "stp"
            rt1, rt2 = f"{pt}{t}", f"{pt}{u}"
            if mode == 0:
                p.case(["mov x20, x19", f"{pair} {rt1}, {rt2}, [x20, #{off}]"], loads, dumpbuf=not is_load)
            elif mode == 1:
                p.case(["mov x20, x19", f"{pair} {rt1}, {rt2}, [x20, #{off}]!"], loads, dumpbuf=not is_load)
            else:
                p.case(["mov x20, x19", f"{pair} {rt1}, {rt2}, [x20], #{off}"], loads, dumpbuf=not is_load)
    # Literal loads.
    p.case(["ldr x3, lit64", "ldr w4, lit32", "ldrsw x5, lit32", "prfm pldl1keep, lit64"])
    p.case(["mov x21, sp", "str x0, [sp, #-16]!", "ldr x1, [sp], #16", "stp x2, x3, [sp, #-32]!", "ldp x4, x5, [sp], #32"],
           {0: 0x1111, 2: 0x2222, 3: 0x3333})
    p.emit("        b       2f")
    p.emit("lit64:  .quad   0x8877665544332211")
    p.emit("lit32:  .word   0x80706050")
    p.emit("2:")


def gen_dczva(p):
    p.emit("        adrp    x19, buf")
    p.emit("        add     x19, x19, :lo12:buf")
    for off in [0, 64, 5, 70, 128, 191]:
        p.emit("        bl      reset_state")
        p.emit("        adrp    x19, buf")
        p.emit("        add     x19, x19, :lo12:buf")
        p.case([f"add x3, x19, #{off}", "dc zva, x3"], dumpbuf=True)


GROUPS = {
    "addsub": gen_addsub,
    "adc": gen_adc,
    "logic": gen_logic,
    "movewide": gen_movewide,
    "bitfield": gen_bitfield,
    "shiftvar": gen_shiftvar,
    "bits": gen_bits,
    "csel": gen_csel,
    "muldiv": gen_muldiv,
    "branch": gen_branch,
    "adr": gen_adr,
    "loadstore": gen_loadstore,
    "dczva": gen_dczva,
}


def main():
    outdir = sys.argv[1]
    os.makedirs(outdir, exist_ok=True)
    for name, fn in GROUPS.items():
        rng = random.Random(f"{SEED}-{name}")
        p = Program(name, rng)
        fn(p)
        p.write(outdir)
        print(f"{name}: {p.cases} cases")


if __name__ == "__main__":
    main()
