// SPDX-License-Identifier: MIT
#pragma once

#include <FEXCore/fextl/functional.h>
#include <FEXCore/fextl/map.h>
#include <FEXCore/fextl/memory.h>
#include <FEXCore/fextl/set.h>
#include <FEXCore/fextl/string.h>
#include <FEXCore/fextl/vector.h>
#include <FEXCore/fextl/robin_map.h>
#include <FEXCore/Utils/CompilerDefs.h>

#include <atomic>
#include <utility>
#include <cstdint>
#include <mutex>
#include <optional>
#include <shared_mutex>
#include <span>
#include <unistd.h>

namespace FEXCore {

namespace Core {
  struct InternalThreadState;
} // namespace Core

namespace HLE {
  struct SourcecodeMap;
} // namespace HLE

enum class GuestRelocationType : uint32_t {
  Rel32,
  Rel64,
  // Skip blocks containing this relocation
  Skip,
};

// Generic information associated with an executable file.
struct ExecutableFileInfo {
  ~ExecutableFileInfo();

#if __clang_major__ < 16
  // Workaround for broken aggregate-initialization with std::piecewise_construct
  ExecutableFileInfo(fextl::unique_ptr<HLE::SourcecodeMap>, uint64_t, fextl::string);
  ExecutableFileInfo() = default;
#endif

  // This legacy field must be assignable through const-references
  mutable fextl::unique_ptr<HLE::SourcecodeMap> SourcecodeMap;

  uint64_t FileId = 0;
  fextl::string Filename;
  fextl::robin_map<uint32_t, GuestRelocationType> Relocations;

  // True when the file carried at least one GuestRelocationType::Skip code
  // relocation. Those entries are dropped from Relocations at runtime (keeping
  // them would make the decoder read the covered displacement as zero, i.e.
  // compile wrong code), so the frontend's HitBadRelocation signal never fires
  // and blocks covering such a site cannot be identified after the fact.
  //
  // A runtime cache writer therefore has to fail closed at file granularity:
  // any file with a Skip relocation is not cacheable at all. FEXOfflineCompiler
  // keeps the Skip entries and filters per block via CheckIfBlockIsCacheable, so
  // it is unaffected by this flag.
  // TODO: Record the Skip offsets and exclude only the blocks whose decoded
  //       guest extent (JITCodeTail::RIP/GuestSize) covers one.
  bool HasUncacheableRelocations = false;
};

// Half-open guest address range [Begin, End).
using GuestAddressRange = std::pair<uint64_t, uint64_t>;

/**
 * Identifier for everything *other than the guest file* that a cache file's
 * contents depend on: the FEX build and every configuration option that changes
 * emitted code.
 *
 * Cache files are named `<FileId>-<ConfigId>`, so a process only ever opens a
 * cache generated by a bit-identical code generator. Together with a
 * content-derived FileId (AbstractCodeCache::ComputeCodeMapId) this makes a
 * mismatched key a cache *miss* rather than a cache load of wrong code.
 *
 * Stable within a process; computed on first use.
 */
FEX_DEFAULT_VISIBILITY uint64_t ComputeCodeCacheConfigId();

struct HostFeatures;
// Records the detected host features that ComputeCodeCacheConfigId folds in.
// Must be called before the first ComputeCodeCacheConfigId; without it the id
// is the invalid sentinel and nothing is ever loaded or written.
FEX_DEFAULT_VISIBILITY void SetCodeCacheHostFeatures(const HostFeatures&);

// Information associated with a specific section of an executable file
struct ExecutableFileSectionInfo {
  const ExecutableFileInfo& FileInfo;

  // Start address that the file is mapped to.
  // NOTE: Since executable files may be mapped multiple times, this can depend on the queried section.
  uintptr_t FileStartVA;

  // Start address of the section mapping
  uintptr_t BeginVA;

  // End address that of the section mapping
  uintptr_t EndVA;

  // Optional owner of FileInfo. A frontend whose file infos can be retired
  // by another thread while a section is in flight (the Linux frontend's
  // MappedResource, freed by munmap) sets it so FileInfo stays valid for the
  // section's lifetime; aggregate initialisers that omit it are unchanged.
  fextl::shared_ptr<const ExecutableFileInfo> Keepalive {};
};

using CodeMapFileId = uint64_t;

/**
 * Code maps capture information required for offline code cache generation
 * and are written to disk during execution of FEX.
 *
 * Almost all CodeMap data will be an Entry that indicates blocks to be
 * compiled for cache generation. The reserved value `LoadExternalLibrary`
 * indicates that an instance of ExternalLibraryInfo follows (the entry data
 * itself should be skipped in that case).
 */
struct CodeMap {
  // Describes the location of an entry block compiled during execution
  struct FEX_PACKED Entry {
    CodeMapFileId FileId;
    uint32_t BlockOffset;
  };

  // Describes an external library referenced during execution
  struct ExternalLibraryInfo {
    CodeMapFileId ExternalFileId;

    // null-terminated file path; EITHER relative to the main executable OR an absolute path OR starting with a magic identifier:
    // - WINE/: Path to Wine/Proton installation
    // - WINEPREFIX/: Path to Wine/Proton prefix
    // - SLR/: Path to Steam Linux Runtime
    // At runtime, FEX will always dump absolute paths
    char Path[];
    // Followed by padding to a 4 byte boundary
  };

  // Followed by ExternalLibraryInfo
  static constexpr Entry LoadExternalLibrary = {0xffff'ffff'ffff'ffff, 0xffff'ffff};

  struct FEX_PACKED SetExecutableFileId {
    Entry Marker = {0xffff'ffff'ffff'ffff, 0xffff'fffe};
    CodeMapFileId ExecutableFileId;
  };

  struct ParsedContents {
    fextl::string Filename;
    fextl::set<uint64_t> Blocks;
    bool IsExecutable = false;
  };

  // Follows scheme fileid[-nomb]
  // The nomb ("no multiblock") suffix signifies that the code map is for use without multiblock, only.
  static fextl::string GetBaseFilename(const ExecutableFileInfo& MainExecutable, bool AddNombSuffix);

  static fextl::map<CodeMapFileId, ParsedContents> ParseCodeMap(std::ifstream& File);
};

struct CodeMapOpener {
  virtual ~CodeMapOpener() = default;
  virtual int OpenCodeMapFile() = 0;
};

class CodeMapWriter {
public:
  CodeMapWriter(CodeMapOpener&, bool OpenEagerly = false);
  ~CodeMapWriter();

  // Checks if writing is enabled. Calls to this functions may also be interpreted as signals that writes are about to happen
  bool IsWriteEnabled(const ExecutableFileSectionInfo&);

  void ResetAfterFork() {
    if (CodeMapFD.value_or(-1) != -1) {
      close(CodeMapFD.value());
      CodeMapFD.reset();
    }
    BufferOffset = 0;
    KnownFileIds.clear();
  }

  bool IsBackingFD(int FD) const {
    if (FD == CodeMapFD) {
      LogMan::Msg::DFmt("Hiding directory entry for code map FD");
      return true;
    }
    return false;
  }

  void AppendBlock(const FEXCore::ExecutableFileSectionInfo&, uint64_t Entry);
  void AppendLibraryLoad(const FEXCore::ExecutableFileInfo&);
  void AppendSetMainExecutable(const FEXCore::ExecutableFileInfo&);

  // Thread-safely commit any pending data to disk
  void Flush(size_t Offset);

private:
  // Queues data into an internal ring buffer.
  // Call Flush() to commit the data to disk.
  void AppendData(std::span<const std::byte> Data);

  // Commit given data range to disk
  void Flush(size_t Offset, std::unique_lock<std::shared_mutex>&);

  std::shared_mutex Mutex;
  fextl::vector<std::byte> Buffer;
  std::atomic<size_t> BufferOffset {0};

  fextl::set<CodeMapFileId> KnownFileIds;

  // std::nullopt: We haven't requested a CodeMapFD yet
  // value is -1:  We requested a CodeMapFD but FEXServer told us not to write any data
  // other values: Code map writing is active
  std::optional<int> CodeMapFD;

  CodeMapOpener& FileOpener;
};

// One file for AbstractCodeCache::SaveNewBlocks.
struct CodeCacheSaveTarget {
  ExecutableFileSectionInfo Section;
  fextl::vector<GuestAddressRange> GuestRanges;
  fextl::string BasePath;
};

// Why AbstractCodeCache::SaveNewBlocks runs.
enum class CodeCacheSaveKind {
  // A checkpoint while the image runs. The targets are every mapped file. A
  // file with too few new blocks keeps them for a later pass.
  Periodic,
  // The image is ending (exit_group, execve): every file's last chance.
  Final,
  // The targets are about to be unmapped (dlclose): their last chance. Blocks
  // of other files wait for a later pass.
  Unmap,
};

// The lock that serialises code-cache save I/O (held across SaveNewBlocks, see
// FEXCore::CodeCache::SaveIOLock). Forward-declared here so the interface can
// expose it without pulling in SignalScopeGuards.h.
class ForkableUniqueMutex;

class AbstractCodeCache {
public:
  virtual ~AbstractCodeCache() = default;

  /**
   * Identity of a mapped guest file for the code map and the code cache
   * filename: a hash of its (device, inode, size, mtime, ctime).
   *
   * It is cheap (no file content is read) and deliberately not relied on for
   * correctness: every cached block carries a hash of the guest instruction
   * bytes it was translated from and is only installed if the process's memory
   * still holds those bytes. A stale identity can therefore only cost misses.
   * FD may be -1, in which case the id is derived from the path alone.
   */
  virtual uint64_t ComputeCodeMapId(std::string_view Filename, int FD) = 0;

  /**
   * Writes one self-contained cache segment holding every block in GuestRanges
   * (all of them when empty) to TargetFD. Used by POWERarmOfflineCompiler.
   * SerializedBaseAddress must be 0.
   */
  virtual bool SaveData(Core::InternalThreadState&, int TargetFD, const ExecutableFileSectionInfo&, uint64_t SerializedBaseAddress,
                        std::span<const GuestAddressRange> GuestRanges = {}) = 0;

  /**
   * Runtime writer. For each target file, appends the blocks this process
   * compiled for it,
   * that are not already in its on-disk cache at BasePath, as a new segment
   * (BasePath, BasePath.1, ... ; compacted back into BasePath when full).
   * Safe against concurrent writers in other processes. Forgets the compiled
   * blocks it considered, written or not, except those a later pass can still
   * save (see CodeCacheSaveKind). Returns the number of segments written.
   */
  virtual size_t SaveNewBlocks(Core::InternalThreadState&, std::span<const CodeCacheSaveTarget> Targets, CodeCacheSaveKind Kind) = 0;

  /**
   * Folds every segment of the file cache at BasePath into one, under the
   * namespace lock (skipped if busy). Used after ahead-of-time translation, so
   * runtime appends do not start by compacting a large AOT namespace.
   */
  virtual bool CompactAllSegments(const fextl::string& BasePath, uint64_t FileId) = 0;

  /**
   * Function to be called before compiling any code for caching purposes
   */
  virtual void InitiateCacheGeneration() = 0;

  /**
   * True once enough new blocks have been compiled (or enough time has passed)
   * that a caller running at a safe point should checkpoint the caches it owns.
   * Cheap enough to poll from a syscall handler. Call NotifyCachesSaved() after
   * a save pass to rearm.
   *
   * IgnoreInterval drops the time/count thresholds but NOT the requirement that
   * something new was compiled, or kept unsaved by an earlier pass.
   */
  virtual bool WantsSave(bool IgnoreInterval) = 0;
  virtual void NotifyCachesSaved() = 0;

  // The lock held across a SaveNewBlocks pass. The syscall-layer save callers
  // take it around the pass so that save I/O -- which can block on the
  // cross-process namespace lock -- no longer holds the shared
  // CodeInvalidationMutex and starves in-process invalidations (issue #1).
  // fork drains it (LockBeforeFork) before snapshotting, so a save that is
  // mid-fork can never leak the lock into the child.
  virtual FEXCore::ForkableUniqueMutex& GetSaveIOLock() = 0;

  // In a fork child: forget the parent's unsaved compiles, so the child only
  // writes what it compiled itself.
  virtual void ResetAfterFork() = 0;

  // POWERARM_CODECACHESTATS=1: one line on stderr at exit with this process's
  // load/miss/reject/save counts.
  virtual void DumpStats() = 0;
};

// The code cache's segment writer is this binary re-exec'd with this as
// argv[1] (see the writer-process block comment in CodeCache.cpp). main() must
// hand such an invocation to CodeCacheWriterMain before it sets anything up:
// the writer publishes finished cache files and needs no part of the emulator.
inline constexpr char CodeCacheWriterArgument[] = "--codecache-writer";
int CodeCacheWriterMain(int ArgC, char** ArgV);

} // namespace FEXCore
